Fabien/feature/meeting tasks
lonestone/rolebase.io pull request #5
Opened 2022-03-01 10:45 UTC by fabien-kerinec

- Amélioration du type d'étape "Tâches" dans le déroulé d'une réunions permettant d'ajouter des tâches à une réunion.
![image](https://user-images.githubusercontent.com/10675550/156153856-6f780039-abb3-4ed1-b0cf-b78ba9ecb79b.png)

- Ajout de bouton de créations de tâches et de discussion en bas d'une fenêtre meeting 
![image](https://user-images.githubusercontent.com/10675550/156154165-5122d745-d912-4ab7-8e1e-fb7b3df29d02.png)

- Ajout d'un bouton cliquable dans le header lorsqu'un meeting est en cours. Il permet de réouvrir la modal du meeting
![image](https://user-images.githubusercontent.com/10675550/156154589-f48c17c0-06bf-4e4d-9efc-1bb4dd5f3366.png)

- Ajout de l'historique de log dans une réunion lorsque celle ci est démarrée
![image](https://user-images.githubusercontent.com/10675550/156154448-7df44358-93c5-42e1-9124-708865851bf1.png)

- Ajout de la création de tâches en tant qu'éléments dans les logs d'historique (Cf. Capture ci dessus)

2022-03-01 21:30 UTC, Godefroy requested changes
Belle PR, t'es bien rentré dans le projet ! 👏 

Je t'ai laissé des commentaires avec des propositions de modification.

Je te propose également ces améliorations :

- [ ] Ajouter un script de migration dans `migration.ts` pour mettre `meetingId` à `null` dans tous les membres en prod.
- [ ] Ne pas afficher les boutons d'ajout de tâche et de discussion lorsque la réunion est terminée.
- [ ] Ajouter du margin-right sur le bouton "Réunion en cours", autant qu'à droite du champ de recherche.
- [ ] Lors de la création d'une tâche, fournir un defaultCircleId à la modale
- [ ] Ajouter un log pour la suppression de tâche (comme la suppression d'un membre ou cercle)
- [ ] Ajouter un log pour le changement de status d'une tâche : "Machin à marqué la tâche Truc comme En cours"
- [ ] Permettre l'annulation d'une action dans l'historique de réunion comme dans l'historique général

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/MeetingStepContent.tsx
> +  meetingStatus: boolean
Je propose de nommer cette propriété `meetingActive`

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/MeetingStepContentTasks.tsx
> +  disableSort,
La propriété `editable` est déjà là pour ça (pareil dans les threads)

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/MeetingStepContentTasks.tsx
> +      disableSort={disableSort}
On peut tester si `onChange` est `undefined` pour éviter de créer cette propriété `disableSort`

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/TaskSortableItem.tsx
> +  disabled: boolean
Par convention, on met en général les events à la fin des props

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/TaskSortableItem.tsx
> +      disabled
Pourquoi le disabled ?

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/TasksMultiSelect.tsx
> +  disableSort: boolean
Pas besoin là non plus du `disableSort`

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/TasksMultiSelect.tsx
> +    if (tasksIds)
Dans le reste de l'app, il y a plutôt cette syntaxe pour éviter de l'indentation :
`if (!tasksIds) return []`

2022-03-01 21:30 UTC, Godefroy commented on src/components/molecules/ThreadSortableItem.tsx
> +  disable,
`disabled` pour avoir le même naming que dans TaskSortableItem

2022-03-01 21:30 UTC, Godefroy commented on src/components/organisms/Header.tsx
> +      ) : null}
Tu peux mettre ce bloc dans le <Flex> pour éviter de rajouter une indentation avec le fragment.

Les modales ouvrent un Portal, donc peu importe où c'est.

Tu peux aussi rajouter un peu de sauts de ligne.

2022-03-01 21:30 UTC, Godefroy commented on src/components/organisms/MeetingContent.tsx
> +            </HStack>
Je propose d'en faire un composant (molecule)

2022-03-01 21:30 UTC, Godefroy commented on src/components/organisms/MeetingContent.tsx
> +                )
Je propose d'en faire un composant (molecule)

2022-03-01 21:30 UTC, Godefroy commented on src/components/organisms/TaskContent.tsx
> +      if (currentMember) {
Tu peux tester l'existence de currentMember au début de la fonction et éviter une indentation

2022-03-01 21:30 UTC, Godefroy commented on src/components/organisms/TaskContent.tsx
> +        }
Les changes peuvent aller directement dans l'appel à createLog

2022-03-01 21:30 UTC, Godefroy commented on src/hooks/useCurrentMember.ts
> +    return currentMember
Cette modification ne me semble pas utile

2022-03-02 08:22 UTC, fabien-kerinec commented on functions/.gitignore
> +.runtimeconfig.json
ok c'était pour prevenir le cas ou le fichier était restant sur une machine que je l'avais remis.

2022-03-02 09:25 UTC, fabien-kerinec commented on src/api/entities/members.ts
> +export async function setInMeetingStatus(
Pour moi il a besoin du `getMember` pour vérifier qu'il n'est pas déjà dans un meeting.
Sinon on écrase automatiquement la valeur du meetingId et il n'appartient potentiellement plus à la réunion en cours en cas de superposition de réunions

2022-03-02 16:47 UTC, fabien-kerinec commented
L'ensemble des review / upgrades ont été traité mise à part : 

- [ ] Update des tasks qu'il faut cadrer ensemble
- [ ] Vérifier le fonctionnement de la migration

2022-03-07 17:54 UTC, Godefroy requested changes

2022-03-07 17:54 UTC, Godefroy commented on src/api/entities/members.ts
> +      if (!member?.meetingId) {
Cette condition ne me semble pas utile, on veut mettre le membre dans le meeting quoiqu'il arrive, non ?

2022-03-07 17:54 UTC, Godefroy commented on src/api/entities/members.ts
> +          meetingId: meetingId,
Tu peux utiliser l'expression short hand

2022-03-07 17:54 UTC, Godefroy commented on src/components/atoms/TaskLink.tsx
> +  const url = useMemo(() => `/orgs/${orgId}/tasks/${id}`, [id, orgId])
Pas besoin de useMemo, c'est probablement plus lourd de mémoizer la valeur que de refaire la string, tu peux mettre l'url directement dans la propriété `to`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingActivitiesCreate.tsx
> +  currentMember?: MemberEntry
Tu n'as besoin que de l'id, je propose de remplacer par une propriété `memberId`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingActivitiesCreate.tsx
> +  meeting?: MeetingEntry
Tu n'as pas pas besoin du `meeting`, juste du `circleId`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingActivitiesCreate.tsx
> +  // Subscribe meeting steps
Mauvais commentaire

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingLogs.tsx
> +export default function Mettinglogs({ logs, logsLoading }: Props) {
*`MeetingLogs`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingLogs.tsx
> +      </Heading>
Tu peux éviter la répétition de ce heading (il est répété 3 fois) en mettant la condition après

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingLogs.tsx
> +export default function Mettinglogs({ logs, logsLoading }: Props) {
D'ailleurs je propose de sortir le `Heading` pour le remettre dans la modale, et d'en faire un composant `LogsList` réutilisé dans la `LogsPage`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepSortableItem.tsx
> +  }
Tu peux sortir la fonction du composant car elle ne dépend pas d'un d'un state ou d'une prop.

Et je propose d'en faire un objet comme dans `LogText`, ça permettra de mettre plus facilement en place l'i18n.

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepSortableItem.tsx
> +
Tu peux donc supprimer `MeetingStepTypeSelect.tsx`

Je propose plus simple (sans la Box) :
```ts
<Text flex={1} pl={5}>{getTitle(stepType)}</Text>
```

Et tu rajoutes :
- `flex={1}` sur l'`<Input>` juste après
- `align="center"` sur la `<Stack>` parente.

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepsConfigController.tsx
> +  console.log(errors)
👆

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepsConfigController.tsx
> +      </Text>
Tu peux utiliser le composant `TextErrors` qui est fait pour ça

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepsConfigController.tsx
> +      </Button> */}
À supprimer

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/MeetingStepsConfigController.tsx
> +  .min(1, 'Ajouter au moins une étape à la réunion')
L'erreur n'était pas utile car on ne pouvait pas supprimer l'item quand il n'y en avait qu'un. Mais ça serait peut-être un comportement à changer vu maintenant qu'on ne peut pas changer le type ?

À ce moment là il faut afficher le bouton de suppression tout le temps en enlevant condition ternaire du `onRemove`

2022-03-07 17:54 UTC, Godefroy commented on shared/log.ts
> +      status: string
`status` n'est utile que pour `TaskUpdate`, pas besoin pour les autres.

`status` ne devrait à mon avis pas contenir du texte ("terminé", etc) qui n'est pas un contenu utilisateur.
Utilise plutôt l'enum de status quand il existera. Et pour l'affichage, tu pourras utiliser l'objet de traduction qui sera utilisé dans le menu de status.

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/TaskSortableItem.tsx
> +  const handleToggleDone = useCallback(() => {
Tu peux rajouter un peu d'espace autour des fonctions longues comme `handleToggleDone`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/TasksMultiSelect.tsx
> +              disabled={typeof onChange !== 'undefined' ? false : true}
`disabled={!onChange}`

2022-03-07 17:54 UTC, Godefroy commented on src/components/molecules/ThreadsMultiSelect.tsx
> +              disabled={typeof onChange !== 'undefined' ? false : true}
`disabled={!onChange}`

2022-03-07 17:54 UTC, Godefroy commented on src/components/organisms/Header.tsx
> +        </Button>
Je propose d'en faire plutôt un lien avec le `Button` sans `onClick` dans un `Link` (react-router-dom).

La réunion en cours c'est un peu particulier, je me dis que ça serait bien d'afficher direct en pleine page quand on ouvre depuis le header (les autres liens du header font ça)

2022-03-07 17:54 UTC, Godefroy commented on src/components/organisms/MeetingContent.tsx
> +            {!meeting.ended && (
`{!meeting.ended && meeting.currentStepId && (`

2022-03-07 17:54 UTC, Godefroy commented on src/components/organisms/TaskContent.tsx
> +            prevData: { doneDate: task.doneDate ? task.doneDate : null },
`prevData: { doneDate: task.doneDate || null },`

2022-03-25 13:09 UTC, closed without merging