Fixes/clipboard copy
lonestone/rolebase.io pull request #67
Opened 2023-01-19 14:54 UTC by NoeGrangier

Resolves #66

2023-01-26 22:43 UTC, Godefroy requested changes
Après ta modif, tu peux squash tes commits et force push pour mettre à jour la PR avec un seul commit propre stp ?

2023-01-26 22:43 UTC, Godefroy commented on src/hooks/useCopyUrl.ts
> +import { useEffect, useMemo } from 'react'
useMemo n'est pas utile, tu devrais avoir une erreur eslint.
Peux-tu check ta config eslint et mettre l'option de vscode "source.organizeImports" à l'enregistrement ?

2023-01-27 16:19 UTC, NoeGrangier commented on src/hooks/useCopyUrl.ts
> +import { useEffect, useMemo } from 'react'
C'est good normalement :)

2023-01-27 20:25 UTC, Godefroy commented on src/hooks/useCopyUrl.ts
> +    toast({ title: t('common.toastCopied'), status: 'info', duration: 1500 })
T'es sûr d'enlever les deps ?
Ca veut dire à mon avis que si un composant parent déclenche un rerender et qu'on a copié avant, ça redéclenche le toast.

2023-01-28 14:12 UTC, NoeGrangier commented on src/hooks/useCopyUrl.ts
> +    toast({ title: t('common.toastCopied'), status: 'info', duration: 1500 })
C'est juste le formatage eslint, hasCopied est toujours en deps

2023-01-31 20:59 UTC, Godefroy commented on src/hooks/useCopyUrl.ts
> +    toast({ title: t('common.toastCopied'), status: 'info', duration: 1500 })
J'ai mal vu, effectivement !

2023-01-31 21:00 UTC, Godefroy requested changes
Le commit ne doit pas s'appeler "Squash"

2023-02-11 09:44 UTC, merged