Feat/add-creator-profile-picture-in-thread-list
lonestone/rolebase.io pull request #72
Opened 2023-02-16 10:24 UTC by Code-Hello

- add thead's initiator member profile picture in thread list

2023-02-16 10:49 UTC, NoeGrangier approved these changes

2023-02-19 17:06 UTC, Godefroy requested changes

2023-02-19 17:06 UTC, Godefroy commented on src/components/molecules/thread/ThreadItem.tsx
> +              <ParticipantsNumber
On utilise ce composant plutôt pour montrer la liste des participants, il me paraît préférable que ça reste une convention dans l'app.

Là tu peux utiliser `MemberByIdAvatar` (tu vas avoir besoin de rebase main, car c'est un nouveau composant).

2023-02-19 17:06 UTC, Godefroy commented on src/components/molecules/ParticipantsNumber.tsx
> +  withRightIcon?: boolean
Je propose de renommer en `showInitiator` pour être plus parlant.

2023-02-23 17:16 UTC, Code-Hello commented on src/components/molecules/thread/ThreadItem.tsx
> +              <ParticipantsNumber
Je n'ai pas trouvé ce composant malgré mon rebase
J'ai donc utilisé `MemberAvatar` qui me semble aussi cohérent

2023-02-23 21:50 UTC, Godefroy requested changes

2023-02-23 21:50 UTC, Godefroy commented on src/components/molecules/ParticipantsNumber.tsx
> +        rightIcon={withRightIcon && <Box mr={2}>{participants.length}</Box>}
Les modifs de ce fichier sont maintenant inutiles

2023-02-28 21:51 UTC, Godefroy approved these changes

2023-02-28 21:51 UTC, merged