Feat/meeting invited notification
lonestone/rolebase.io pull request #80
Opened 2023-03-09 17:58 UTC by Code-Hello

add "meetinginvited" notification :
- when creating a meeting
- when updating meeting participants (only send a "meetinginvited" notification to those new participants)

upgrade nhost

2023-03-10 18:43 UTC, Godefroy requested changes

2023-03-10 18:43 UTC, Godefroy commented on functions/_utils/notification/meetingStartedNotification.ts
> +      : `${settings.url}/orgs/${this.parameters.orgId}/meetings/${this.parameters.meetingId}`
Je propose de factoriser un peu plus : 

```ts
return `${settings.url}${
    this.parameters.org
      ? getOrgPath(this.parameters.org)
      : `/orgs/${this.parameters.orgId}`
  }/meetings/${this.parameters.meetingId}`
```

2023-03-10 18:43 UTC, Godefroy commented on functions/routes/updateMeeting.ts
> +export default route(async (context) => {
Plutôt que de faire une route, je propose de faire un event trigger sur les updates de meeting (comme pour l'indexation d'un meeting dans le moteur de recherche). Comme ça pas besoin de faire un appel depuis le front, et tu as directement les anciennes et nouvelles valeurs dans le payload d'event.

2023-03-10 18:43 UTC, Godefroy commented on functions/routes/updateMeetingRecurring.ts
> +export default route(async (context) => {
Pas besoin d'envoyer des notifs à la création ou à la modification d'un recurring meeting.
En revanche il faut envoyer une notification comme pour les réunions normales lors de la création de la prochaine occurrence d'un recurring meeting.
Ca se passe dans `createNextRecurringMeetings`.

2023-03-13 09:04 UTC, Code-Hello commented on functions/routes/updateMeeting.ts
> +export default route(async (context) => {
J'avais tenté de le faire avec un event trigger mais le soucis dans l'event trigger c'est que je dois call la route pour envoyer la notif' attend un header d'authorization que je n'ai pas via l'event trigger 
De ce fait j'ai donc finalement revu ma copie et suis passée par cette option

2023-03-13 13:25 UTC, Code-Hello commented on functions/routes/updateMeeting.ts
> +export default route(async (context) => {
J'avais tenté de le faire j'aurais effectivement dû aller jusqu'au bout de l'idée

2023-03-15 22:46 UTC, Godefroy requested changes

2023-03-15 22:46 UTC, Godefroy commented on functions/_utils/notification/getNotificationMeetingRecurringData.ts
> +export async function getNotificationMeetingRecurringData(
Ce fichier n'est plus utile, et le fragment `MeetingRecurringNotificationData` non plus.

2023-03-15 22:46 UTC, Godefroy commented on functions/_utils/getParticipantIdsByScope.ts
> +export async function getParticipantIdsByScope(
Le contenu de cette fonction est fortement redondant avec le hook `getAllCircleMembersParticipants`.
Je propose d'abstraire le code commun dans une nouvelle fonction `@shared/helpers/getParticipantsByScope`qui renvoie `ParticipantMember[]`.

La query `getOrg` peut être appelée plutôt qu'ici dans `getMeetingParticipantIdsDiff` depuis `sendMeetingInvitedNotification` et `getMeetingParticipantIdsDiff`. Cela permettra d'éviter le double appel depuis `getMeetingParticipantIdsDiff`.

On peut donc enlever le paramètre `orgId` et rajouter les paramètres `circles: CircleFullFragment[], members: MemberFragment[]`.

Il ne devrait plus rester grand chose dans `useParticipants`.

2023-03-15 22:46 UTC, Godefroy commented on functions/_utils/guardOrg.ts
> +  context: FunctionContext | { userId: string },
Cet ajout ne me semble pas utile

2023-03-15 22:46 UTC, Godefroy commented on functions/routes/events/updateMeetingParticipants.ts
> +  if (newParticipantIds) {
Check inutile car tu le fais déjà juste avant.

2023-03-15 22:46 UTC, Godefroy commented on functions/_utils/notification/notificationPayloadBuilder.ts
> +type NotificationMeetingInvitedPayload = {}
Ces types vides ne me paraissent pas très utiles

2023-03-15 22:46 UTC, Godefroy commented on functions/routes/events/updateMeetingParticipants.ts
> +  const oldMeeting: Meeting_Set_Input = event.event.data.old
Il vaut mieux utiliser `MeetingFragment` à la place de `Meeting_Set_Input` (pareil plus bas)

2023-03-15 22:46 UTC, Godefroy commented on functions/routes/sendMeetingInvitedNotification.ts
> +export default route(async (context): Promise<void> => {
On doit pouvoir se passer de cette route en observant aussi les inserts avec le même event trigger.
Il suffira de vérifier qu'il n'y a pas de `recurringId` pour éviter de notifier en cas d'invitation à une occurrence d'une réunion récurrente.

2023-03-15 22:46 UTC, Godefroy commented on functions/routes/sendMeetingInvitedNotification.ts
> +export default route(async (context): Promise<void> => {
`meetingInvitedSend` n'aura alors besoin d'être appelée qu'une seule fois, donc peut-être pas besoin de la mettre dans une fonction à part.

2023-03-16 10:27 UTC, Code-Hello commented on functions/_utils/notification/getNotificationMeetingRecurringData.ts
> +export async function getNotificationMeetingRecurringData(
Je l'avais laissé au cas où mais en effet mieux vaut l'enlever

2023-03-16 10:29 UTC, Code-Hello commented on functions/_utils/guardOrg.ts
> +  context: FunctionContext | { userId: string },
Ici soit je mets ça soit je mets `Partial<FunctionContext>` car j'utilise cette fonction ailleurs sans avoir tout le context mais uniquement le userId 
Or le type `FunctionContext ` attend plus que le userId

2023-03-16 10:31 UTC, Code-Hello commented on functions/routes/events/updateMeetingParticipants.ts
> +  const oldMeeting: Meeting_Set_Input = event.event.data.old
Ce qui est retourné dans l'event n'est pas un `MeetingFragment` mais un `Meeting_Set_input` d'où l'utilisation de ce type

2023-03-16 10:34 UTC, Code-Hello commented on functions/routes/sendMeetingInvitedNotification.ts
> +export default route(async (context): Promise<void> => {
Yep en effet on doit pouvoir avoir cette logique pour toutes les notif' qui sont liées à insert ou update de db et ne passer que par les event trigger dans ces cas là

2023-03-16 21:58 UTC, Godefroy requested changes

2023-03-16 21:58 UTC, Godefroy commented on functions/_shared/fragments/meeting.gql
> +    members(where: { userId: { _eq: $userId } }) {
Même chose que dans #74

2023-03-16 21:58 UTC, Godefroy commented on functions/_shared/model/notification.ts
> +}
Même chose que dans #74, je suis pas sûr que ce soit le bon endroit ni que ce type soit indispensable.

2023-03-20 12:39 UTC, Code-Hello commented on functions/_shared/model/notification.ts
> +}
Le type peut être pas mal à avoir selon moi : ça évite de dupliquer du code et qu'on mette un peu ce qu'on veut comme type alors que c'est bien celui-ci qui est attendu à plusieurs endroits
Par contre en effet ce n'est pas le bon endroit je change ça

2023-03-23 14:41 UTC, Godefroy requested changes

2023-03-23 17:03 UTC, Godefroy approved these changes

2023-03-23 17:03 UTC, merged