Feat/thread message notification
lonestone/rolebase.io pull request #88
Opened 2023-03-24 11:50 UTC by Code-Hello

add notification for new thread
- lets the users know there is a new topic for them

add notification for new activity on thread
- lets the users know new activities have been posted on one of their topics
- here we use a digest to not spam users

2023-04-15 17:46 UTC, Godefroy requested changes

2023-04-15 17:46 UTC, Godefroy commented on docs/email-templates/Digest.mjml
> +          <mj-text font-size="18px" font-weight="700" color="white" align="center" padding="10px">{{step.events.0.title}}</mj-text>
`step.event.0` prend le premier event j'imagine ? Tu ne boucles pas sur tous les events fournis ?

2023-04-15 17:46 UTC, Godefroy commented on functions/_i18n/locales/fr.json
> +        "openTask": "Open la tâche",
*Ouvrir

2023-04-15 17:46 UTC, Godefroy commented on functions/_i18n/locales/fr.json
> +      "digestContentPlural": "nouveaux messages sur le sujet : {{title}}."
Ne t'embêtes pas avec la gestion du pluriel ici, je pense que ça suffira de mettre "Nouveau message dans le sujet : {{title}}"

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/getEntityWithParticipantsRecipientIds.ts
> +export async function getEntityWithParticipantsRecipientIds(
Ok c'est pratique, mais il faudra faire attention à l'utiliser à bon escient car c'est très lourd et dans certains cas il faudra l'éviter mutualiser l'appel à `getOrgCirclesFullAndMembers`.
Tu peux mettre un commentaire qui explique ça au dessus de la définition de la fonction

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/getParticipantIdsDiff.ts
> +export async function getParticipantIdsDiff<
Idem que pour getEntityWithParticipantsRecipientIds

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/getParticipantIdsDiff.ts
> +  T extends MeetingFragment | ThreadFragment
Tu peux mettre `EntityWithParticipants` plutôt que `MeetingFragment | ThreadFragment`

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/notification/checkSendNotificationEvent.ts
> +  T = MeetingFragment | TaskFragment | ThreadFragment | ThreadActivityFragment
Pas besoin d'ajouter cette dépendance à Meeting, Task etc.

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/notification/meeting/meetingInvitedUpdateAction.ts
> +  const newParticipantIds = await getParticipantIdsDiff<MeetingFragment>(
Je pense pas que tu aies besoin de préciser le type générique

2023-04-15 17:46 UTC, Godefroy commented on functions/_utils/notification/thread/getNotificationThreadActivityData.ts
> +      ...ThreadActivity
Tu as besoin de tout ce qu'il y a dans l'activité ?

2023-04-15 17:46 UTC, Godefroy commented on functions/routes/events/sendMeetingInvitedNotification.ts
> +  if (event.data.new!.recurringId) {
C'est pas tip top de mettre des `!` partout. Pourquoi pas mettre old et new dans l'objet retourné par checkSendNotificationEvent, avec un contrôle du typing au niveau de la signature de la fonction. Comme ça tu t'assures que new est bien défini et tu l'utilises à la place de event.data.new

2023-04-15 17:46 UTC, Godefroy commented on functions/routes/events/sendThreadActivityNotification.ts
> +  // Currently we just send notification when a new thread is inserted in DB
*new thread activity

2023-04-15 17:46 UTC, Godefroy commented on functions/routes/events/sendThreadActivityNotification.ts
> +  })
Pas besoin de guardOrg car la route ne peut être appelée que par Hasura.  Et donc pas besoin de GET_THREAD_ACTIVITY_ORG

2023-04-15 17:46 UTC, Godefroy commented on functions/routes/events/sendThreadNotification.ts
> +  })
Pas besoin de guardOrg. (tu peux check les autres events aussi)

2023-04-15 17:46 UTC, Godefroy commented on functions/routes/sendMeetingStartedNotification.ts
> +import { MeetingStartedNotification } from '@utils/notification/meeting/meetingStartedNotification'
Tu as bien `"source.organizeImports": true` dans ta config VSCode ?

2023-04-17 07:56 UTC, Code-Hello commented on docs/email-templates/Digest.mjml
> +          <mj-text font-size="18px" font-weight="700" color="white" align="center" padding="10px">{{step.events.0.title}}</mj-text>
Yep et non parce que tous les events ont le même contenu pas besoin

2023-04-18 12:47 UTC, Godefroy requested changes

2023-04-18 12:47 UTC, Godefroy commented on functions/_utils/getEntityWithParticipantsRecipientIds.ts
> +  }
inutile

2023-04-18 12:47 UTC, Godefroy commented on functions/_utils/getParticipantIdsDiff.ts
> +  }
inutile

2023-04-18 12:47 UTC, Godefroy commented on functions/_utils/notification/thread/threadInsertAction.ts
> +  }
inutile

2023-04-18 12:47 UTC, Godefroy commented on functions/routes/events/sendThreadActivityNotification.ts
> +  }
inutile

2023-04-18 12:47 UTC, Godefroy commented on nhost/metadata/databases/default/tables/public_thread_activity.yaml
> +          - type
enlever update

2023-04-19 08:55 UTC, merged