Definir et changer le statut d'un sujet
lonestone/rolebase.io pull request #90
Opened 2023-05-03 15:50 UTC by Chloengr

Ticket : https://app.clickup.com/t/860qn6y1t

2023-05-04 19:01 UTC, Godefroy commented on src/components/molecules/CircleThreadStatus.tsx
> +  }, [status])
J'aimerais bien que ça se comporte comme `ThreadStatusMenu` avec un menu déroulant quand on clique sur le rond, ça permettrait de modifier le statut directement depuis la page des sujets, les sujets en réunion ou la sections sujets d'un rôle.
Je préconise d'utiliser isMember (const isMember = useOrgMember()) pour gérer les membres en lecture seule.

2023-05-09 09:38 UTC, Chloengr commented on src/components/molecules/thread/ThreadItem.tsx
> +              <Center w={6} h={6} mr={2} zIndex={'overlay'}>
Pour le zIndex, c'est parce que c'est dans une LinkBox avec a un hover qui empêche d'avoir le tooltip et la propriété existe ça permet de ne pas mettre de valeur au pif mais de lui faire comprendre quelle position prendre

2023-05-09 09:40 UTC, Chloengr commented on src/i18n/locales/en.json
> +    }
j'y ai pensé après aussi du coup c'est sur la prochaine pr :)

2023-05-13 14:55 UTC, Godefroy requested changes
Super !
Encore 2 petits trucs et on est bon

2023-05-13 14:55 UTC, Godefroy commented on nhost/metadata/databases/default/tables/public_thread.yaml
> -                      _eq: Owner
Pourquoi enlever ces checks ?

2023-05-13 15:08 UTC, Godefroy requested changes

2023-05-13 15:08 UTC, Godefroy commented on nhost/migrations/default/1683633602774_squashed/up.sql
> +INSERT INTO "public"."thread_status"("value", "comment") VALUES (E'Done', null);
Peux-tu mettre "Active" plutôt que "Done" ici dans cette PR ?
J'ai vu que tu as fait la modif dans la PR #91), mais il ne faut pas modifier une migration, car la modification ne sera pas prise en compte lors du déploiement, une migration n'étant exécutée qu'une seule fois.

2023-05-17 20:47 UTC, Godefroy requested changes

2023-05-17 20:47 UTC, Godefroy commented on nhost/metadata/databases/default/tables/public_thread.yaml
> +        - createdAt
On ne veut pas laisser la possibilité de régler createdAt. C'est la valeur par défaut `now()` qui s'applique.
(dsl j'avais pas vu ça avant)

2023-05-17 20:47 UTC, Godefroy commented on nhost/metadata/databases/default/tables/public_thread.yaml
> +        - orgId
On ne veut pas autoriser la modification de ces 3 propriétés.

2023-05-26 19:15 UTC, Godefroy approved these changes
GG 🎉

2023-05-26 19:15 UTC, merged