see status history on thread
lonestone/rolebase.io pull request #91
Opened 2023-05-04 14:31 UTC by Chloengr

Ticket : https://app.clickup.com/t/860qnxfr4 

/!\ parent branch is chloe/createdthread-status

2023-05-04 20:59 UTC, Godefroy requested changes

2023-05-04 20:59 UTC, Godefroy commented on src/components/atoms/ThreadStatusText.tsx
> +}
Pour être cohérent avec les tasks, je propose de copier TaskStatusTag (et renommer en ThreadStatusTag)

2023-05-04 20:59 UTC, Godefroy commented on src/components/molecules/thread/ThreadStatusLogItem.tsx
> +}
On pourra enlever ce composant au profit d'un composant `ThreadActivityChangeStatus` comme je propose dans un commentaire plus bas.

2023-05-04 20:59 UTC, Godefroy commented on src/components/organisms/thread/ThreadContent.tsx
> +          </>
Pourquoi ajouter un fragment ?

2023-05-04 20:59 UTC, Godefroy commented on src/components/molecules/ScrollableLayout.tsx
> +  inner?: React.ReactElement
Cette prop ne me paraît pas claire et ne me paraît pas être du ressort de ScrollableLayout.
Il vaut mieux afficher les logs dans ThreadContent

2023-05-04 20:59 UTC, Godefroy commented on src/components/organisms/thread/ThreadStatusLogs.tsx
> +  })
Cette subscription a une limite et concerne tous les types de log. On risquerait donc ne pas avoir tous les résultats qu'on veut et on récupérerait beaucoup trop de data.
Voici ce que je propose :
Requêter tous les logs du thead dans la subscription threadActivities (src/api/thread_activity.gql).
Les logs récupérés au niveau de `useThreadState` peuvent alors être ajoutés sous forme d'activities.
Il faut pour ça créer un nouveau type "ChangeStatus" dans thread_activity_type qu'on utilisera côté front uniquement. Puis ajouter un composant d'affichage `ThreadActivityChangeStatus` un peu comme `ThreadActivityThread`.

2023-05-04 20:59 UTC, Godefroy commented on functions/_shared/model/log.ts
> +  thread: ThreadFragment
L'approche d'utiliser les logs de la table log me va bien. J'ai l'impression qu'il manque juste quelques modifs `useCancelLog` suite à cet ajout.
Tu as fait un `npm run tsc` pour vérifier que tout compile bien ? (il devrait juste y avoir des erreurs dans 3 fichiers en rapport avec les subscriptions stripe)

2023-05-13 15:45 UTC, Godefroy requested changes
Merci pour les modifs. J'ai repéré quelques petits problèmes et j'ai quelques changements d'archi à te proposer :

2023-05-13 15:45 UTC, Godefroy commented on src/components/molecules/thread/ThreadActivityChangeStatus.tsx
> +    <ThreadActivityLayout activity={activity} allowDelete>
L'activity existant uniquement côté front, allowDelete ne fonctionne pas ici, non ?

2023-05-13 15:45 UTC, Godefroy commented on src/components/organisms/thread/ThreadContent.tsx
> -
Check bien le diff avant de commit, ça peut t'éviter ce genre de petite modif 😉
Perso j'utilise à fond la section "Source Control" de VSCode, c'est super pratique.

2023-05-13 15:45 UTC, Godefroy commented on nhost/migrations/default/1683633602774_squashed/up.sql
> +INSERT INTO "public"."thread_status"("value", "comment") VALUES (E'Active', null);
Il ne faut pas modifier une migration, car la modification ne sera pas prise en compte lors du déploiement, une migration n'étant exécutée qu'une seule fois.

2023-05-13 15:45 UTC, Godefroy commented on src/components/organisms/thread/ThreadActivities.tsx
> +      })
Ca peut être mis dans le `useMemo`

2023-05-13 15:45 UTC, Godefroy commented on src/components/organisms/thread/ThreadActivities.tsx
> +      })
Les dates au format ISO string peuvent être directement comparées sans instance de Date

2023-05-13 15:45 UTC, Godefroy commented on src/components/organisms/thread/ThreadActivities.tsx
> +      })
Tout ça (map + concat) devrait plutôt être la responsabilité de `useThreadState` à mon avis.
On aurait alors plus besoin d'exporter et récupérer `threadLogs`.
Les modifications de `ThreadActivities` pourraient alors être complètement annulées.

2023-05-13 15:45 UTC, Godefroy commented on src/hooks/useThreadState.ts
> +  const threadLogs = threadLogsResult.data?.log || undefined
Les 2 subscriptions (`threadActivities` et `threadLogs`) peuvent être combinées dans `threadActivities`

2023-05-13 15:45 UTC, Godefroy commented on src/i18n/locales/fr.json
> +    "text": "a changé le sujet de <prevStatus /> à <status />"
Je propose un wording plus simple :
```
a changé le statut du sujet : <status />
```

2023-05-13 15:45 UTC, Godefroy commented on src/api/log.gql
> +  log(where: { threadId: { _eq: $threadId } }, order_by: { createdAt: asc }) {
`order_by` ne me semble pas utile ici car tu fais un `sort` après

2023-05-13 15:45 UTC, Godefroy commented on src/components/molecules/log/LogText.tsx
> +          i18nKey={`${i18nPrefix}.${type}`}
Il manque la trad `LogText.ThreadActivityChangeStatus` dans les locales

2023-05-13 15:45 UTC, Godefroy commented on src/components/molecules/log/LogText.tsx
> +          i18nKey={`${i18nPrefix}.${type}`}
Tu peux vérifier que ça s'affiche bien dans la webapp en allant dans le menu "Paramètres > Historique"

2023-05-13 15:45 UTC, Godefroy commented on src/components/molecules/thread/ThreadActivityChangeStatus.tsx
> +              task: <ThreadLink id={display.id} name={display.name} />,
Cette propriété n'est pas utilisée / pas utile.

2023-05-16 14:25 UTC, Chloengr commented on src/api/thread_activity.gql
> +  thread(where: { id: { _eq: $id } }, order_by: { createdAt: asc }, limit: 1) {
thread_by_pk

2023-05-17 20:52 UTC, Godefroy approved these changes

2023-05-17 20:52 UTC, merged