filter by thread status
lonestone/rolebase.io pull request #92
Opened 2023-05-11 09:17 UTC by Chloengr

Ticket : https://app.clickup.com/t/860qnxjv6

/!\ parent branch is chloe/thread-status-activity

2023-05-13 15:57 UTC, Godefroy requested changes

2023-05-13 15:57 UTC, Godefroy commented on src/i18n/locales/fr.json
> -  },
Tu as du supprimer ça par erreur 😄

2023-05-13 15:57 UTC, Godefroy commented on src/components/pages/ThreadsPage.tsx
> -        </Menu>
Pour renforcer la cohérence avec les pages Tâches et Réunions, je propose de :
- Remettre le code du menu dans ce composant (et donc supprimer le nouveau fichier)
- Enlever le filtre archived : on ne propose pas cette option sur les autres pages, et archived joue le rôle de suppression, donc on pourrait se reposer sur l'historique (logs) si on veut récupérer un thread archivé.
- Faire un menu de statut exactement comme sur la page Tâches en mode Liste

2023-05-15 15:05 UTC, Chloengr commented on src/components/pages/ThreadsPage.tsx
> -        </Menu>
Je pense que ca va pas être exactement pareil parce que il faut pouvoir sélectionner 1 ou plusieurs statuts

2023-05-17 20:57 UTC, Godefroy commented
Il y a quelques conflits suite au merge de la branche `chloe/thread-status-activity` dans `chloe/createthread-status`

2023-05-26 19:17 UTC, Godefroy approved these changes

2023-05-26 19:17 UTC, Godefroy commented
Pourras-tu rebase pour que je puisse merge stp ?

2023-05-31 18:25 UTC, Godefroy approved these changes

2023-05-31 18:26 UTC, merged