Verify email modal
lonestone/rolebase.io pull request #98
Opened 2023-05-25 10:32 UTC by Chloengr

Ticket : https://app.clickup.com/t/860prz2n0

2023-05-26 19:42 UTC, Godefroy requested changes

2023-05-26 19:42 UTC, Godefroy commented on src/components/organisms/user/VerifiyEmailModal.tsx
> +      >
Peux-tu essayer de factoriser ce style dans un nouveau composant à utiliser également dans RateAppModal ?

2023-05-26 19:42 UTC, Godefroy commented on src/i18n/locales/fr.json
> +    "text": "Cliquez sur le lien que nous venons de vous envoyer par email pour vérifier votre adresse.",
Je crois qu'aucun email n'est envoyé actuellement à l'inscription. Tu as testé ?
Et si l'utilisateur se connecte un certain temps après s'être inscrit sans avoir vérifié son email, ce texte n'aide pas assez.

Je propose donc de :
- Changer le text : "Vous avez reçu un email, cliquez sur le lien pour vérifier votre adresse."
- Ajouter un bouton "Recevoir un nouvel email"

2023-05-31 13:52 UTC, Chloengr commented on src/i18n/locales/fr.json
> +    "text": "Cliquez sur le lien que nous venons de vous envoyer par email pour vérifier votre adresse.",
Dans mon souvenir pour Lonestone, j'en avais reçu un et on l'a bien d'implémenté dans le login et register avec nhost

2023-05-31 18:37 UTC, Godefroy approved these changes

2023-06-15 20:59 UTC, Godefroy commented
Plus qu'à rebase et on est bon :)

2023-06-19 15:28 UTC, Chloengr commented
C'st ok pour le mail de confirmation, du moins avec le hook useSendVerificationEmail() impossible de le faire fonctionner après une inscription du coup j'ai utilisé auth.sendEmailVerif(). Pour le check needsEmailVerification, il ne fonctionne que quand on a choisit dans nhost de vérifier les emails dans les settings

2023-06-21 10:26 UTC, Godefroy requested changes

2023-06-21 10:26 UTC, Godefroy commented on src/components/organisms/user/SignupForm.tsx
> +  const { auth } = useNhostClient()
Pourquoi ce changement ?  Tu utilises `useSendVerificationEmail` dans `VerifiyEmailModal.tsx`, c'est différent ?

2023-06-21 10:26 UTC, Godefroy commented on src/components/organisms/user/SignupForm.tsx
> +      await sendVerifyEmail(user?.email!)
`?` et `!` vraiment utiles ?

2023-06-21 10:26 UTC, Godefroy commented on src/components/organisms/user/LoginForm.tsx
> -                {t(isSent ? 'LoginForm.emailSent' : 'LoginForm.sendEmail')}
Si les 3 trads utilisées dans cette Alert ne sont plus utilisées, il faut les retirer des fichiers de locales.

2023-06-28 08:53 UTC, Chloengr commented on src/components/organisms/user/SignupForm.tsx
> +  const { auth } = useNhostClient()
le `useSendVerificationEmail `est dispo qu'après l'authentification et pas pendant, c'est pour ça que quand j'ai un utilisateur connecté je peux l'utiliser mais avant vu qu'on n'a pas mis la vérification d'email requis il est pas dispo

2023-07-05 20:48 UTC, Godefroy approved these changes

2023-07-05 20:48 UTC, merged